host: 0.0.0.0
port: 5000
map:
  image_path: /maps/map_scanned_by_robot/scan_by_robot.png
  yaml_path: /maps/map_scanned_by_robot/scan_by_robot.yaml
  sp_path: /maps/map_scanned_by_robot/scan_by_robot.txt
gpt:
  endpoint: http://172.18.35.200:8000/uploads/llm_queries
vpr:
  enable_vpr: false
  endpoint: http://10.16.242.37:5000/localize
  use_depth: false